### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by bui** [bui/taiko3-discord-rpc#1]
- [x] improve wording for rpc states
- [x] use wiiu3 icons for difficulties (and provide a way to dump?)
- [x] some error handling
- [x] localisation maybe

**Comment by bui** [comment]
there's also things i wanna do like pulling the user's custom donchan and displaying it in the large image (would require users to have their own apps...) and pulling song results/scores to do something with them? not necessarily discord-related, could write to a file maybe
